apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend-container
          image: 038462784201.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: backend-secrets
